//
//  MenuBarItemsReader.swift
//  Furl
//
//  Enumerates other apps' menu bar items ("menu bar extras") using only the
//  documented Accessibility API — no screen capture and no private
//  window-server APIs.
//

import AppKit
import ApplicationServices

/// A single menu bar item discovered via the Accessibility API.
struct MenuBarItemEntry {
    /// The accessibility element for the item, used to locate it.
    let element: AXUIElement
    /// The name of the application that owns the item.
    let appName: String
    /// The icon of the owning application, if available.
    let appIcon: NSImage?
    /// The item's index among its app's menu bar items.
    let index: Int
    /// The item's developer-assigned accessibility identifier, when it is
    /// usable as an identity (non-empty, unique within the app, and not a
    /// generic autogenerated "Item-N" name). `nil` falls back to the index.
    let axIdentifier: String?

    /// The bundle identifier of the owning application, if available.
    let bundleID: String?

    /// The process identifier of the owning application.
    let pid: pid_t

    /// The label to show in the dropdown and settings — the app's name.
    var displayTitle: String {
        appName
    }

    /// A stable identifier used to persist per-item preferences across
    /// launches. Prefers the accessibility identifier (stable even when the
    /// app adds/removes/reorders its items); falls back to the item's index.
    /// (The underlying `AXUIElement` is recreated each launch and can't be stored.)
    var identity: String {
        if let axIdentifier {
            return "\(bundleID ?? appName)#id:\(axIdentifier)"
        }
        return legacyIdentity
    }

    /// The index-based identity used before the identifier scheme. Kept for
    /// reading previously-persisted settings; matched entries are migrated.
    var legacyIdentity: String {
        "\(bundleID ?? appName)#\(index)"
    }
}

/// A snapshot of a running application, captured on the main thread so the
/// Accessibility enumeration can run on a background queue without touching
/// AppKit's main-thread-affined APIs.
struct MenuBarAppInfo {
    let pid: pid_t
    let name: String
    let bundleID: String?
    let icon: NSImage?
}

/// Reads menu bar items through the Accessibility API.
enum MenuBarItemsReader {
    /// A Boolean value indicating whether the app has Accessibility access.
    static var hasAccessibility: Bool {
        AXIsProcessTrusted()
    }

    /// Prompts the user to grant Accessibility access, opening System Settings.
    static func requestAccessibility() {
        let key = kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String
        _ = AXIsProcessTrustedWithOptions([key: true] as CFDictionary)
    }

    private static func attribute(_ element: AXUIElement, _ name: String) -> CFTypeRef? {
        var value: CFTypeRef?
        guard AXUIElementCopyAttributeValue(element, name as CFString, &value) == .success else {
            return nil
        }
        return value
    }

    /// Returns a snapshot of candidate applications. Must be called on the main
    /// thread, since it reads AppKit state.
    @MainActor
    static func appSnapshot() -> [MenuBarAppInfo] {
        let ownBundleID = Bundle.main.bundleIdentifier
        return NSWorkspace.shared.runningApplications.compactMap { app in
            let pid = app.processIdentifier
            guard
                pid > 0,
                app.bundleIdentifier != ownBundleID,
                app.activationPolicy != .prohibited
            else {
                return nil
            }
            return MenuBarAppInfo(
                pid: pid,
                name: app.localizedName ?? app.bundleIdentifier ?? "Unknown",
                bundleID: app.bundleIdentifier,
                icon: app.icon
            )
        }
    }

    /// macOS-managed apps whose menu bar items are always visible and can't be
    /// repositioned (Control Center hosts the Clock, Wi-Fi, Battery, Sound,
    /// Focus, and friends). They live right of our icon, so they're excluded
    /// from the Furl menu entirely.
    private static let systemBundleIDs: Set<String> = [
        "com.apple.controlcenter",
    ]

    /// NSStatusItem autosave names default to "Item-0", "Item-1", … — those
    /// identifiers are just indices in disguise and no stabler than the index.
    private static func isGenericIdentifier(_ identifier: String) -> Bool {
        guard identifier.hasPrefix("Item-") else {
            return false
        }
        return identifier.dropFirst(5).allSatisfy(\.isNumber)
    }

    /// Enumerates the menu bar items belonging to the given applications.
    /// Safe to call off the main thread.
    static func readItems(from apps: [MenuBarAppInfo]) -> [MenuBarItemEntry] {
        var entries = [MenuBarItemEntry]()

        for app in apps {
            if let bundleID = app.bundleID, systemBundleIDs.contains(bundleID) {
                continue
            }

            let axApp = AXUIElementCreateApplication(app.pid)
            // Bound every message to this app so a single unresponsive app
            // can't stall the enumeration.
            AXUIElementSetMessagingTimeout(axApp, 0.5)

            guard
                let extras = attribute(axApp, "AXExtrasMenuBar"),
                CFGetTypeID(extras) == AXUIElementGetTypeID()
            else {
                continue
            }

            // swiftlint:disable:next force_cast
            let extrasElement = extras as! AXUIElement
            // Timeouts are per-element; the extras element doesn't inherit the
            // app element's, so bound it too.
            AXUIElementSetMessagingTimeout(extrasElement, 0.5)
            guard
                let children = attribute(extrasElement, kAXChildrenAttribute as String) as? [AXUIElement],
                !children.isEmpty
            else {
                continue
            }

            // An identifier is only usable as an identity if it appears once
            // within the app — duplicates would collide.
            let rawIdentifiers: [String?] = children.map { child in
                guard
                    let value = attribute(child, kAXIdentifierAttribute as String) as? String,
                    !value.isEmpty,
                    !isGenericIdentifier(value)
                else {
                    return nil
                }
                return value
            }
            var identifierCounts = [String: Int]()
            for case let identifier? in rawIdentifiers {
                identifierCounts[identifier, default: 0] += 1
            }

            for (index, item) in children.enumerated() {
                let identifier = rawIdentifiers[index].flatMap { identifierCounts[$0] == 1 ? $0 : nil }
                entries.append(
                    MenuBarItemEntry(
                        element: item,
                        appName: app.name,
                        appIcon: app.icon,
                        index: index,
                        axIdentifier: identifier,
                        bundleID: app.bundleID,
                        pid: app.pid
                    )
                )
            }
        }

        return entries
    }

    /// Re-enumerates a single app and returns the entry matching the given
    /// (possibly stale) one. Used when a cached AX element has died because
    /// the app recreated its item since the last refresh.
    @MainActor
    static func refreshedEntry(for entry: MenuBarItemEntry) -> MenuBarItemEntry? {
        guard let app = NSRunningApplication(processIdentifier: entry.pid) else {
            return nil
        }
        let info = MenuBarAppInfo(
            pid: entry.pid,
            name: app.localizedName ?? entry.appName,
            bundleID: app.bundleIdentifier,
            icon: app.icon
        )
        return readItems(from: [info]).first {
            $0.identity == entry.identity || $0.legacyIdentity == entry.legacyIdentity
        }
    }
}
